# Generated by Django 4.1.7 on 2023-05-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_post_author_remove_post_email_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='twitext',
        ),
    ]
