# Generated by Django 4.1.7 on 2023-05-18 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 19, 9, 31, 437684, tzinfo=datetime.timezone.utc)),
        ),
    ]
