# Generated by Django 4.1.7 on 2023-05-18 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 13, 19, 1972, tzinfo=datetime.timezone.utc)),
        ),
    ]
