# Generated by Django 4.1.7 on 2023-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_likes_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pos_id',
            field=models.CharField(default=1, max_length=100, verbose_name='ID поста'),
        ),
    ]
