# Generated by Django 4.1.7 on 2023-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pos_id',
            field=models.IntegerField(default=1, max_length=100, verbose_name='ID поста'),
        ),
    ]
