# Generated by Django 4.1.7 on 2023-05-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_comment_pos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comm_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
