# Generated by Django 4.1.7 on 2023-05-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_rename_author_comment_comm_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comm_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
